Pipeline fixes

diff --git a/build/azure-pipelines/common/sanity-tests.yml b/build/azure-pipelines/common/sanity-tests.yml
--- a/build/azure-pipelines/common/sanity-tests.yml
+++ b/build/azure-pipelines/common/sanity-tests.yml
@@ -27,7 +27,7 @@ jobs:
           isProduction: false
           condition: succeededOrFailed()
     steps:
-      - checkout: self
+      - template: ./common/checkout.yml@self
 
       - task: NodeTool@0
         inputs:
@@ -35,19 +35,55 @@ jobs:
           versionFilePath: .nvmrc
         displayName: Install Node.js
 
-      - ${{ if eq(parameters.os, 'windows') }}:
-        - script: |
-            mkdir "$(SANITY_TEST_LOGS)"
-          displayName: Create Logs Directory
+      - script: node build/setup-npm-registry.ts $NPM_REGISTRY
+        condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
+        displayName: Setup NPM Registry
 
-      - ${{ else }}:
-        - script: |
-            mkdir -p "$(SANITY_TEST_LOGS)"
-          displayName: Create Logs Directory
+      - script: mkdir -p .build && node build/azure-pipelines/common/computeNodeModulesCacheKey.ts compile $(node -p process.arch) > .build/packagelockhash
+        displayName: Prepare node_modules cache key
 
-      - script: npm install
-        displayName: Install Dependencies
-        workingDirectory: $(Build.SourcesDirectory)/test/sanity
+      - task: Cache@2
+        inputs:
+          key: '"node_modules" | .build/packagelockhash'
+          path: .build/node_modules_cache
+          cacheHitVar: NODE_MODULES_RESTORED
+        displayName: Restore node_modules cache
+
+      - script: tar -xzf .build/node_modules_cache/cache.tgz
+        condition: and(succeeded(), eq(variables.NODE_MODULES_RESTORED, 'true'))
+        displayName: Extract node_modules cache
+
+      - script: |
+          set -e
+          # Set the private NPM registry to the global npmrc file
+          # so that authentication works for subfolders like build/, remote/, extensions/ etc
+          # which does not have their own .npmrc file
+          npm config set registry "$NPM_REGISTRY"
+          echo "##vso[task.setvariable variable=NPMRC_PATH]$(npm config get userconfig)"
+        condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
+        displayName: Setup NPM
+
+      - task: npmAuthenticate@0
+        inputs:
+          workingFile: $(NPMRC_PATH)
+        condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
+        displayName: Setup NPM Authentication
+
+      - script: |
+          set -e
+
+          for i in {1..5}; do # try 5 times
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
+              exit 1
+            fi
+            echo "Npm install failed $i, trying again..."
+          done
+        env:
+          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+        displayName: Install dependencies
+        condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
 
       - script: npm run sanity-test -- --commit ${{ parameters.commit }} --quality ${{ parameters.quality }} --verbose --test-results $(SANITY_TEST_LOGS)/sanity-test.xml
         displayName: Run Sanity Tests
