fix: oss build

diff --git a/build/azure-pipelines/linux/product-build-linux.yml b/build/azure-pipelines/linux/product-build-linux.yml
--- a/build/azure-pipelines/linux/product-build-linux.yml
+++ b/build/azure-pipelines/linux/product-build-linux.yml
@@ -41,20 +41,33 @@ steps:
     - script: tar -xzf $(Build.ArtifactStagingDirectory)/compilation.tar.gz
       displayName: Extract compilation output
 
-    - script: |
-        set -e
-        # Start X server
-        sudo apt-get update
-        sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libkrb5-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
-        sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
-        sudo chmod +x /etc/init.d/xvfb
-        sudo update-rc.d xvfb defaults
-        sudo service xvfb start
-        # Start dbus session
-        sudo mkdir -p /var/run/dbus
-        DBUS_LAUNCH_RESULT=$(sudo dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address)
-        echo "##vso[task.setvariable variable=DBUS_SESSION_BUS_ADDRESS]$DBUS_LAUNCH_RESULT"
-      displayName: Setup system services
+  - script: |
+      set -e
+      # Start X server
+      sudo apt-get update
+      sudo apt-get install -y pkg-config libxss1 dbus xvfb libgtk-3-0 libgbm1
+      sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
+      sudo chmod +x /etc/init.d/xvfb
+      sudo update-rc.d xvfb defaults
+      sudo service xvfb start
+      # Start dbus session
+      sudo mkdir -p /var/run/dbus
+      DBUS_LAUNCH_RESULT=$(sudo dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address)
+      echo "##vso[task.setvariable variable=DBUS_SESSION_BUS_ADDRESS]$DBUS_LAUNCH_RESULT"
+    displayName: Setup system services
+
+  - script: |
+      set -e
+      arch=$(VSCODE_ARCH)
+      if [ "$arch" = "x64" ]; then
+        arch="amd64"
+      fi
+      sudo dpkg --add-architecture $arch
+      sudo apt-get update
+      sudo apt-get install -y libxkbfile-dev:$arch \
+        libsecret-1-dev:$arch \
+        libkrb5-dev:$arch
+    displayName: Install architecture dependencies
 
   - script: node build/setup-npm-registry.js $NPM_REGISTRY
     condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
@@ -102,44 +115,64 @@ steps:
         containerCommand: uname
       condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
 
-  - script: |
-      set -e
-
-      for i in {1..5}; do # try 5 times
-        yarn --cwd build --frozen-lockfile --check-files && break
-        if [ $i -eq 3 ]; then
-          echo "Yarn failed too many times" >&2
-          exit 1
-        fi
-        echo "Yarn failed $i, trying again..."
-      done
-
-      docker run -e GITHUB_TOKEN -e npm_config_arch -e NPM_REGISTRY \
-      -e VSCODE_REMOTE_DEPENDENCIES_CONTAINER_NAME -e VSCODE_HOST_MOUNT \
-      -e ELECTRON_SKIP_BINARY_DOWNLOAD -e PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD \
-      -v /mnt/vss/_work/1/s:/home/builduser/vscode -v /mnt/vss/_work/1/s/.build/.netrc:/home/builduser/.netrc \
-      -v /var/run/docker.sock:/var/run/docker.sock \
-      -u 1000:1000 \
-      -w /home/builduser/vscode vscodehub.azurecr.io/vscode-linux-build-agent:bionic-$(VSCODE_ARCH)-temp \
-      /bin/bash -c "./build/azure-pipelines/linux/install.sh"
-
-      sudo chown -R $USER:$USER /mnt/vss/_work/1/s
-    env:
-      npm_config_arch: $(NPM_ARCH)
-      NPM_REGISTRY: "$(NPM_REGISTRY)"
-      ELECTRON_SKIP_BINARY_DOWNLOAD: 1
-      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
-      GITHUB_TOKEN: "$(github-distro-mixin-password)"
-      VSCODE_HOST_MOUNT: "/mnt/vss/_work/1/s"
-      ${{ if and(ne(parameters.VSCODE_QUALITY, 'oss'), or(eq(parameters.VSCODE_ARCH, 'x64'), eq(parameters.VSCODE_ARCH, 'arm64'))) }}:
-        VSCODE_REMOTE_DEPENDENCIES_CONTAINER_NAME: vscodehub.azurecr.io/vscode-linux-build-agent:centos7-devtoolset8-$(VSCODE_ARCH)
-    displayName: Install dependencies
-    condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
-
   - ${{ if ne(parameters.VSCODE_QUALITY, 'oss') }}:
+    - script: |
+        set -e
+
+        for i in {1..5}; do # try 5 times
+          yarn --cwd build --frozen-lockfile --check-files && break
+          if [ $i -eq 3 ]; then
+            echo "Yarn failed too many times" >&2
+            exit 1
+          fi
+          echo "Yarn failed $i, trying again..."
+        done
+
+        docker run -e GITHUB_TOKEN -e npm_config_arch -e NPM_REGISTRY \
+        -e VSCODE_REMOTE_DEPENDENCIES_CONTAINER_NAME -e VSCODE_HOST_MOUNT \
+        -e ELECTRON_SKIP_BINARY_DOWNLOAD -e PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD \
+        -v /mnt/vss/_work/1/s:/home/builduser/vscode -v /mnt/vss/_work/1/s/.build/.netrc:/home/builduser/.netrc \
+        -v /var/run/docker.sock:/var/run/docker.sock \
+        -u 1000:1000 \
+        -w /home/builduser/vscode vscodehub.azurecr.io/vscode-linux-build-agent:bionic-$(VSCODE_ARCH)-temp \
+        /bin/bash -c "./build/azure-pipelines/linux/install.sh"
+
+        sudo chown -R $USER:$USER /mnt/vss/_work/1/s
+      env:
+        npm_config_arch: $(NPM_ARCH)
+        NPM_REGISTRY: "$(NPM_REGISTRY)"
+        ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+        GITHUB_TOKEN: "$(github-distro-mixin-password)"
+        VSCODE_HOST_MOUNT: "/mnt/vss/_work/1/s"
+        ${{ if or(eq(parameters.VSCODE_ARCH, 'x64'), eq(parameters.VSCODE_ARCH, 'arm64')) }}:
+          VSCODE_REMOTE_DEPENDENCIES_CONTAINER_NAME: vscodehub.azurecr.io/vscode-linux-build-agent:centos7-devtoolset8-$(VSCODE_ARCH)
+      displayName: Install dependencies
+      condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
+
     - script: node build/azure-pipelines/distro/mixin-npm
       condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
       displayName: Mixin distro node modules
+
+  - ${{ else }}:
+    - script: |
+        set -e
+
+        for i in {1..5}; do # try 5 times
+          yarn --frozen-lockfile --check-files && break
+          if [ $i -eq 3 ]; then
+            echo "Yarn failed too many times" >&2
+            exit 1
+          fi
+          echo "Yarn failed $i, trying again..."
+        done
+      env:
+        npm_config_arch: $(NPM_ARCH)
+        ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+        GITHUB_TOKEN: "$(github-distro-mixin-password)"
+      displayName: Install dependencies
+      condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
 
   - script: |
       set -e
