chore: test with signing disabled

diff --git a/build/azure-pipelines/linux/product-build-linux.yml b/build/azure-pipelines/linux/product-build-linux.yml
--- a/build/azure-pipelines/linux/product-build-linux.yml
+++ b/build/azure-pipelines/linux/product-build-linux.yml
@@ -251,103 +251,103 @@ steps:
         GITHUB_TOKEN: "$(github-distro-mixin-password)"
       displayName: Transpile client and extensions
 
-  - ${{ if and(ne(parameters.VSCODE_CIBUILD, true), ne(parameters.VSCODE_QUALITY, 'oss')) }}:
-    - script:  |
-        set -e
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-deb"
-      env:
-        GITHUB_TOKEN: "$(github-distro-mixin-password)"
-      displayName: Prepare deb package
+  #- ${{ if and(ne(parameters.VSCODE_CIBUILD, true), ne(parameters.VSCODE_QUALITY, 'oss')) }}:
+    #- script:  |
+    #    set -e
+    #    npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-deb"
+    #  env:
+    #    GITHUB_TOKEN: "$(github-distro-mixin-password)"
+    #  displayName: Prepare deb package
 
-    - script:  |
-        set -e
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-build-deb"
-        file_output=$(file $(ls .build/linux/deb/*/deb/*.deb))
-        if [[ "$file_output" != *"data compression xz"* ]]; then
-          echo "Error: unknown compression. $file_output"
-          exit 1
-        fi
-        echo "##vso[task.setvariable variable=DEB_PATH]$(ls .build/linux/deb/*/deb/*.deb)"
-      displayName: Build deb package
+    #- script:  |
+    #    set -e
+    #    npm run gulp "vscode-linux-$(VSCODE_ARCH)-build-deb"
+    #    file_output=$(file $(ls .build/linux/deb/*/deb/*.deb))
+    #    if [[ "$file_output" != *"data compression xz"* ]]; then
+    #      echo "Error: unknown compression. $file_output"
+    #      exit 1
+    #    fi
+    #    echo "##vso[task.setvariable variable=DEB_PATH]$(ls .build/linux/deb/*/deb/*.deb)"
+    #  displayName: Build deb package
 
-    - script:  |
-        set -e
-        TRIPLE=""
-        if [ "$VSCODE_ARCH" == "x64" ]; then
-          TRIPLE="x86_64-linux-gnu"
-        elif [ "$VSCODE_ARCH" == "arm64" ]; then
-          TRIPLE="aarch64-linux-gnu"
-        elif [ "$VSCODE_ARCH" == "armhf" ]; then
-          TRIPLE="arm-rpi-linux-gnueabihf"
-        fi
-        export VSCODE_SYSROOT_DIR=$(Build.SourcesDirectory)/.build/sysroots
-        export STRIP="$VSCODE_SYSROOT_DIR/$TRIPLE/$TRIPLE/bin/strip"
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-rpm"
-      env:
-        VSCODE_ARCH: $(VSCODE_ARCH)
-      displayName: Prepare rpm package
+    #- script:  |
+    #    set -e
+    #    TRIPLE=""
+    #    if [ "$VSCODE_ARCH" == "x64" ]; then
+    #      TRIPLE="x86_64-linux-gnu"
+    #    elif [ "$VSCODE_ARCH" == "arm64" ]; then
+    #      TRIPLE="aarch64-linux-gnu"
+    #    elif [ "$VSCODE_ARCH" == "armhf" ]; then
+    #      TRIPLE="arm-rpi-linux-gnueabihf"
+    #    fi
+    #    export VSCODE_SYSROOT_DIR=$(Build.SourcesDirectory)/.build/sysroots
+    #    export STRIP="$VSCODE_SYSROOT_DIR/$TRIPLE/$TRIPLE/bin/strip"
+    #    npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-rpm"
+    #  env:
+    #    VSCODE_ARCH: $(VSCODE_ARCH)
+    #  displayName: Prepare rpm package
 
-    - script:  |
-        set -e
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-build-rpm"
-        echo "##vso[task.setvariable variable=RPM_PATH]$(ls .build/linux/rpm/*/*.rpm)"
-      displayName: Build rpm package
+    #- script:  |
+    #    set -e
+    #    npm run gulp "vscode-linux-$(VSCODE_ARCH)-build-rpm"
+    #    echo "##vso[task.setvariable variable=RPM_PATH]$(ls .build/linux/rpm/*/*.rpm)"
+    #  displayName: Build rpm package
 
-    - ${{ if eq(parameters.VSCODE_ARCH, 'x64') }}:
-      - task: Docker@1
-        inputs:
-          azureSubscriptionEndpoint: vscode
-          azureContainerRegistry: vscodehub.azurecr.io
-          command: login
-        displayName: Login to Container Registry
+    #- ${{ if eq(parameters.VSCODE_ARCH, 'x64') }}:
+    #  - task: Docker@1
+    #    inputs:
+    #      azureSubscriptionEndpoint: vscode
+    #      azureContainerRegistry: vscodehub.azurecr.io
+    #      command: login
+    #    displayName: Login to Container Registry
 
-      - script: |
-          set -e
-          npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-snap"
-          sudo -E docker run -e VSCODE_ARCH -e VSCODE_QUALITY -v $(pwd):/work -w /work vscodehub.azurecr.io/vscode-linux-build-agent:snapcraft-x64 /bin/bash -c "./build/azure-pipelines/linux/build-snap.sh"
+    #  - script: |
+    #      set -e
+    #      npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-snap"
+    #      sudo -E docker run -e VSCODE_ARCH -e VSCODE_QUALITY -v $(pwd):/work -w /work vscodehub.azurecr.io/vscode-linux-build-agent:snapcraft-x64 /bin/bash -c "./build/azure-pipelines/linux/build-snap.sh"
 
-          SNAP_ROOT="$(pwd)/.build/linux/snap/$(VSCODE_ARCH)"
-          SNAP_EXTRACTED_PATH=$(find $SNAP_ROOT -maxdepth 1 -type d -name 'code-*')
-          SNAP_PATH=$(find $SNAP_ROOT -maxdepth 1 -type f -name '*.snap')
+    #      SNAP_ROOT="$(pwd)/.build/linux/snap/$(VSCODE_ARCH)"
+    #      SNAP_EXTRACTED_PATH=$(find $SNAP_ROOT -maxdepth 1 -type d -name 'code-*')
+    #      SNAP_PATH=$(find $SNAP_ROOT -maxdepth 1 -type f -name '*.snap')
 
           # SBOM tool doesn't like recursive symlinks
-          sudo find $SNAP_EXTRACTED_PATH -type l -delete
+    #      sudo find $SNAP_EXTRACTED_PATH -type l -delete
 
-          echo "##vso[task.setvariable variable=SNAP_EXTRACTED_PATH]$SNAP_EXTRACTED_PATH"
-          echo "##vso[task.setvariable variable=SNAP_PATH]$SNAP_PATH"
-        env:
-          VSCODE_ARCH: $(VSCODE_ARCH)
-        displayName: Build snap package
+    #      echo "##vso[task.setvariable variable=SNAP_EXTRACTED_PATH]$SNAP_EXTRACTED_PATH"
+    #      echo "##vso[task.setvariable variable=SNAP_PATH]$SNAP_PATH"
+    #    env:
+    #      VSCODE_ARCH: $(VSCODE_ARCH)
+    #    displayName: Build snap package
 
-    - task: UseDotNet@2
-      inputs:
-        version: 6.x
+    #- task: UseDotNet@2
+    #  inputs:
+    #    version: 6.x
 
-    - task: EsrpCodeSigning@5
-      inputs:
-        UseMSIAuthentication: true
-        ConnectedServiceName: vscode-esrp
-        AppRegistrationClientId: $(ESRP_CLIENT_ID)
-        AppRegistrationTenantId: $(ESRP_TENANT_ID)
-        AuthAKVName: vscode-esrp
-        AuthSignCertName: esrp-sign
-        FolderPath: .
-        Pattern: noop
-      displayName: 'Install ESRP Tooling'
+    #- task: EsrpCodeSigning@5
+    #  inputs:
+    #    UseMSIAuthentication: true
+    #    ConnectedServiceName: vscode-esrp
+    #    AppRegistrationClientId: $(ESRP_CLIENT_ID)
+    #    AppRegistrationTenantId: $(ESRP_TENANT_ID)
+    #    AuthAKVName: vscode-esrp
+    #    AuthSignCertName: esrp-sign
+    #    FolderPath: .
+    #    Pattern: noop
+    #  displayName: 'Install ESRP Tooling'
 
-    - pwsh: |
-        . build/azure-pipelines/win32/exec.ps1
-        $ErrorActionPreference = "Stop"
-        $EsrpCodeSigningTool = (gci -directory -filter EsrpCodeSigning_* $(Agent.RootDirectory)/_tasks | Select-Object -last 1).FullName
-        $Version = (gci -directory $EsrpCodeSigningTool | Select-Object -last 1).FullName
-        echo "##vso[task.setvariable variable=EsrpCliDllPath]$Version/net6.0/esrpcli.dll"
-      displayName: Find ESRP CLI
+    #- pwsh: |
+    #    . build/azure-pipelines/win32/exec.ps1
+    #    $ErrorActionPreference = "Stop"
+    #    $EsrpCodeSigningTool = (gci -directory -filter EsrpCodeSigning_* $(Agent.RootDirectory)/_tasks | Select-Object -last 1).FullName
+    #    $Version = (gci -directory $EsrpCodeSigningTool | Select-Object -last 1).FullName
+    #    echo "##vso[task.setvariable variable=EsrpCliDllPath]$Version/net6.0/esrpcli.dll"
+    #  displayName: Find ESRP CLI
 
-    - script: npx deemon -- npx zx build/azure-pipelines/linux/codesign.js
-      env:
-        EsrpCliDllPath: $(EsrpCliDllPath)
-        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
-      displayName: ✍️ Codesign deb & rpm
+    #- script: npx deemon -- npx zx build/azure-pipelines/linux/codesign.js
+    #  env:
+    #    EsrpCliDllPath: $(EsrpCliDllPath)
+    #    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+    #  displayName: ✍️ Codesign deb & rpm
 
   - ${{ if or(eq(parameters.VSCODE_RUN_ELECTRON_TESTS, true), eq(parameters.VSCODE_RUN_BROWSER_TESTS, true), eq(parameters.VSCODE_RUN_REMOTE_TESTS, true)) }}:
     - template: product-build-linux-test.yml@self
@@ -399,32 +399,32 @@ steps:
       condition: and(succeededOrFailed(), ne(variables['WEB_PATH'], ''))
       displayName: Publish web server archive
 
-    - task: 1ES.PublishPipelineArtifact@1
-      inputs:
-        targetPath: $(DEB_PATH)
-        artifactName: $(ARTIFACT_PREFIX)vscode_client_linux_$(VSCODE_ARCH)_deb-package
-        sbomBuildDropPath: .build/linux/deb
-        sbomPackageName: "VS Code Linux $(VSCODE_ARCH) DEB"
-        sbomPackageVersion: $(Build.SourceVersion)
-      condition: and(succeededOrFailed(), ne(variables['DEB_PATH'], ''))
-      displayName: Publish deb package
+    #- task: 1ES.PublishPipelineArtifact@1
+    #  inputs:
+    #    targetPath: $(DEB_PATH)
+    #    artifactName: $(ARTIFACT_PREFIX)vscode_client_linux_$(VSCODE_ARCH)_deb-package
+    #    sbomBuildDropPath: .build/linux/deb
+    #    sbomPackageName: "VS Code Linux $(VSCODE_ARCH) DEB"
+    #    sbomPackageVersion: $(Build.SourceVersion)
+    #  condition: and(succeededOrFailed(), ne(variables['DEB_PATH'], ''))
+    #  displayName: Publish deb package
 
-    - task: 1ES.PublishPipelineArtifact@1
-      inputs:
-        targetPath: $(RPM_PATH)
-        artifactName: $(ARTIFACT_PREFIX)vscode_client_linux_$(VSCODE_ARCH)_rpm-package
-        sbomBuildDropPath: .build/linux/rpm
-        sbomPackageName: "VS Code Linux $(VSCODE_ARCH) RPM"
-        sbomPackageVersion: $(Build.SourceVersion)
-      condition: and(succeededOrFailed(), ne(variables['RPM_PATH'], ''))
-      displayName: Publish rpm package
+    #- task: 1ES.PublishPipelineArtifact@1
+    #  inputs:
+    #    targetPath: $(RPM_PATH)
+    #    artifactName: $(ARTIFACT_PREFIX)vscode_client_linux_$(VSCODE_ARCH)_rpm-package
+    #    sbomBuildDropPath: .build/linux/rpm
+    #    sbomPackageName: "VS Code Linux $(VSCODE_ARCH) RPM"
+    #    sbomPackageVersion: $(Build.SourceVersion)
+    #  condition: and(succeededOrFailed(), ne(variables['RPM_PATH'], ''))
+    #  displayName: Publish rpm package
 
-    - task: 1ES.PublishPipelineArtifact@1
-      inputs:
-        targetPath: $(SNAP_PATH)
-        artifactName: vscode_client_linux_$(VSCODE_ARCH)_snap
-        sbomBuildDropPath: $(SNAP_EXTRACTED_PATH)
-        sbomPackageName: "VS Code Linux $(VSCODE_ARCH) SNAP"
-        sbomPackageVersion: $(Build.SourceVersion)
-      condition: and(succeededOrFailed(), ne(variables['SNAP_PATH'], ''))
-      displayName: Publish snap package
+    #- task: 1ES.PublishPipelineArtifact@1
+    #  inputs:
+    #    targetPath: $(SNAP_PATH)
+    #    artifactName: vscode_client_linux_$(VSCODE_ARCH)_snap
+    #    sbomBuildDropPath: $(SNAP_EXTRACTED_PATH)
+    #    sbomPackageName: "VS Code Linux $(VSCODE_ARCH) SNAP"
+    #    sbomPackageVersion: $(Build.SourceVersion)
+    #  condition: and(succeededOrFailed(), ne(variables['SNAP_PATH'], ''))
+    #  displayName: Publish snap package
