Restore most hygiene steps

diff --git a/build/azure-pipelines/product-hygiene.yml b/build/azure-pipelines/product-hygiene.yml
--- a/build/azure-pipelines/product-hygiene.yml
+++ b/build/azure-pipelines/product-hygiene.yml
@@ -40,28 +40,27 @@ steps:
 
   - task: Cache@2
     inputs:
-      key: 'nodeModules3 | $(Agent.OS) | .build/arch, .build/terrapin, build/.cachesalt, .yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
+      key: 'genericNodeModules1 | $(Agent.OS) | .build/arch, .build/terrapin, build/.cachesalt, .yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
       path: .build/node_modules_cache
       cacheHitVar: NODE_MODULES_RESTORED
-    displayName: Cache yarn download folder
+    displayName: Cache node_modules archive
 
   - script: |
       set -e
       tar --zstd -xf .build/node_modules_cache/cache.tzst -P -C $BUILD_SOURCESDIRECTORY
-      ls -al build/node_modules
     condition: and(succeeded(), eq(variables.NODE_MODULES_RESTORED, 'true'))
-
-
-  # - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
-  #   inputs:
-  #     keyfile: ".build/arch, .build/terrapin, build/.cachesalt, .yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock"
-  #     targetfolder: "**/node_modules, !**/node_modules/**/node_modules"
-  #     vstsFeed: "npm-vscode"
+    displayName: Extract node_modules archive
 
   - script: |
       set -e
-      cd build
-      yarn --frozen-lockfile && break
+      for i in {1..3}; do # try 3 times, for Terrapin
+        yarn --frozen-lockfile && break
+        if [ $i -eq 3 ]; then
+          echo "Yarn failed too many times" >&2
+          exit 1
+        fi
+        echo "Yarn failed $i, trying again..."
+      done
     env:
       ELECTRON_SKIP_BINARY_DOWNLOAD: 1
       PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
@@ -74,30 +73,31 @@ steps:
       mkdir -p .build/node_modules_cache
       tar --posix --zstd -cf .build/node_modules_cache/cache.tzst -P -C $BUILD_SOURCESDIRECTORY --files-from .build/node_modules_list.txt
     condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
+    displayName: Create node_modules archive
 
-  # # Mixin must run before optimize, because the CSS loader will inline small SVGs
-  # - script: |
-  #     set -e
-  #     node build/azure-pipelines/mixin
-  #   displayName: Mix in quality
+  # Mixin must run before optimize, because the CSS loader will inline small SVGs
+  - script: |
+      set -e
+      node build/azure-pipelines/mixin
+    displayName: Mix in quality
 
-  # - script: |
-  #     set -e
-  #     yarn gulp hygiene
-  #   # yarn monaco-compile-check
-  #   # yarn valid-layers-check
-  #   displayName: Run hygiene, monaco compile & valid layers checks
-  #   condition: and(succeeded(), eq(variables['VSCODE_STEP_ON_IT'], 'false'))
+  - script: |
+      set -e
+      yarn gulp hygiene
+    # yarn monaco-compile-check
+    # yarn valid-layers-check
+    displayName: Run hygiene, monaco compile & valid layers checks
+    condition: and(succeeded(), eq(variables['VSCODE_STEP_ON_IT'], 'false'))
 
-  # - script: |
-  #     set -
-  #     ./build/azure-pipelines/common/extract-telemetry.sh
-  #   displayName: Extract Telemetry
-  #   condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
+  - script: |
+      set -
+      ./build/azure-pipelines/common/extract-telemetry.sh
+    displayName: Extract Telemetry
+    condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
 
-  # - script: |
-  #     set -e
-  #     AZURE_WEBVIEW_STORAGE_ACCESS_KEY="$(vscode-webview-storage-key)" \
-  #     ./build/azure-pipelines/common/publish-webview.sh
-  #   displayName: Publish Webview
-  #   condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
+  - script: |
+      set -e
+      AZURE_WEBVIEW_STORAGE_ACCESS_KEY="$(vscode-webview-storage-key)" \
+      ./build/azure-pipelines/common/publish-webview.sh
+    displayName: Publish Webview
+    condition: and(succeeded(), ne(variables['VSCODE_PUBLISH'], 'false'))
