further simplifications to tar invocation

diff --git a/build/azure-pipelines/product-hygiene.yml b/build/azure-pipelines/product-hygiene.yml
--- a/build/azure-pipelines/product-hygiene.yml
+++ b/build/azure-pipelines/product-hygiene.yml
@@ -9,28 +9,28 @@ steps:
       azureSubscription: "vscode-builds-subscription"
       KeyVaultName: vscode
 
-  - script: |
-      set -e
-      cat << EOF > ~/.netrc
-      machine github.com
-      login vscode
-      password $(github-distro-mixin-password)
-      EOF
+  # - script: |
+  #     set -e
+  #     cat << EOF > ~/.netrc
+  #     machine github.com
+  #     login vscode
+  #     password $(github-distro-mixin-password)
+  #     EOF
 
-      git config user.email "vscode@microsoft.com"
-      git config user.name "VSCode"
-    displayName: Prepare tooling
+  #     git config user.email "vscode@microsoft.com"
+  #     git config user.name "VSCode"
+  #   displayName: Prepare tooling
 
-  - script: |
-      set -e
-      git pull --no-rebase https://github.com/$(VSCODE_MIXIN_REPO).git $(node -p "require('./package.json').distro")
-    displayName: Merge distro
+  # - script: |
+  #     set -e
+  #     git pull --no-rebase https://github.com/$(VSCODE_MIXIN_REPO).git $(node -p "require('./package.json').distro")
+  #   displayName: Merge distro
 
-  - script: |
-      npx https://aka.ms/enablesecurefeed standAlone
-    displayName: Switch to Terrapin packages
-    timeoutInMinutes: 5
-    condition: and(succeeded(), eq(variables['ENABLE_TERRAPIN'], 'true'))
+  # - script: |
+  #     npx https://aka.ms/enablesecurefeed standAlone
+  #   displayName: Switch to Terrapin packages
+  #   timeoutInMinutes: 5
+  #   condition: and(succeeded(), eq(variables['ENABLE_TERRAPIN'], 'true'))
 
   - script: |
       mkdir -p .build
@@ -39,7 +39,7 @@ steps:
 
   - task: Cache@2
     inputs:
-      key: 'genericNodeModules2 | $(Agent.OS) | .build/yarnlockhash'
+      key: 'genericNodeModules3 | $(Agent.OS) | .build/yarnlockhash'
       path: .build/node_modules_cache
       cacheHitVar: NODE_MODULES_RESTORED
     displayName: Cache node_modules archive
@@ -47,24 +47,30 @@ steps:
   - script: |
       set -e
       tar --zstd -xf .build/node_modules_cache/cache.tzst -P -C $BUILD_SOURCESDIRECTORY
+      ls build/node_modules
     condition: and(succeeded(), eq(variables.NODE_MODULES_RESTORED, 'true'))
     displayName: Extract node_modules archive
 
+  # - script: |
+  #     set -e
+  #     for i in {1..3}; do # try 3 times, for Terrapin
+  #       yarn --frozen-lockfile && break
+  #       if [ $i -eq 3 ]; then
+  #         echo "Yarn failed too many times" >&2
+  #         exit 1
+  #       fi
+  #       echo "Yarn failed $i, trying again..."
+  #     done
+  #   env:
+  #     ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+  #     PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+  #   displayName: Install dependencies
+  #   condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
+
   - script: |
       set -e
-      for i in {1..3}; do # try 3 times, for Terrapin
-        yarn --frozen-lockfile && break
-        if [ $i -eq 3 ]; then
-          echo "Yarn failed too many times" >&2
-          exit 1
-        fi
-        echo "Yarn failed $i, trying again..."
-      done
-    env:
-      ELECTRON_SKIP_BINARY_DOWNLOAD: 1
-      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
-    displayName: Install dependencies
-    condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
+      mkdir -p build/node_modules
+      echo "hello" > build/node_modules/test.txt
 
   - script: |
       set -e
