Add macOS electron tests job

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -76,31 +76,118 @@ jobs:
       - name: Check /build/ folder
         run: .github/workflows/check-clean-git-state.sh
 
-      # - name: Compile & Hygiene
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   run: npm exec -- npm-run-all -lp core-ci-pr extensions-ci-pr hygiene eslint valid-layers-check define-class-fields-check vscode-dts-compile-check tsec-compile-check
+      - name: Compile & Hygiene
+        run: npm exec -- npm-run-all -lp core-ci-pr extensions-ci-pr hygiene eslint valid-layers-check define-class-fields-check vscode-dts-compile-check tsec-compile-check
 
-      - name: npm run core-ci-pr
-        run: npm run core-ci-pr
+      # - name: npm run core-ci-pr
+      #   run: npm run core-ci-pr
 
-      - name: npm run extensions-ci-pr
-        run: npm run extensions-ci-pr
+      # - name: npm run extensions-ci-pr
+      #   run: npm run extensions-ci-pr
 
-      - name: npm run hygiene
-        run: npm run hygiene
+      # - name: npm run hygiene
+      #   run: npm run hygiene
 
-      - name: npm run eslint
-        run: npm run eslint
+      # - name: npm run eslint
+      #   run: npm run eslint
 
-      - name: npm run valid-layers-check
-        run: npm run valid-layers-check
+      # - name: npm run valid-layers-check
+      #   run: npm run valid-layers-check
 
-      - name: npm run define-class-fields-check
-        run: npm run define-class-fields-check
+      # - name: npm run define-class-fields-check
+      #   run: npm run define-class-fields-check
 
-      - name: npm run vscode-dts-compile-check
-        run: npm run vscode-dts-compile-check
+      # - name: npm run vscode-dts-compile-check
+      #   run: npm run vscode-dts-compile-check
 
-      - name: npm run tsec-compile-check
-        run: npm run tsec-compile-check
+      # - name: npm run tsec-compile-check
+      #   run: npm run tsec-compile-check
+
+  macos-electron-tests:
+    name: macOS (Electron)
+    runs-on: macos-14-xlarge
+    env:
+      VSCODE_ARCH: arm64
+    steps:
+      - name: Checkout microsoft/vscode
+        uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: .nvmrc
+        env:
+          NODEJS_ORG_MIRROR: https://github.com/joaomoreno/node-mirror/releases/download
+
+      - name: Prepare node_modules cache key
+        run: mkdir -p .build && node build/azure-pipelines/common/computeNodeModulesCacheKey.js darwin $VSCODE_ARCH $(node -p process.arch) > .build/packagelockhash
+
+      - name: Restore node_modules cache
+        id: cache-node-modules
+        uses: actions/cache@v4
+        with:
+          path: .build/node_modules_cache
+          key: "node_modules-${{ hashFiles('.build/packagelockhash') }}"
+
+      - name: Extract node_modules cache
+        if: steps.cache-node-modules.outputs.cache-hit == 'true'
+        run: tar -xzf .build/node_modules_cache/cache.tgz
+
+      - name: Install dependencies
+        if: steps.cache-node-modules.outputs.cache-hit != 'true'
+        env:
+          npm_config_arch: ${{ env.VSCODE_ARCH }}
+          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # Avoid using dlopen to load Kerberos on macOS which can cause missing libraries
+          # https://github.com/mongodb-js/kerberos/commit/04044d2814ad1d01e77f1ce87f26b03d86692cf2
+          # flipped the default to support legacy linux distros which shouldn't happen
+          # on macOS.
+          GYP_DEFINES: "kerberos_use_rtld=false"
+        run: |
+          set -e
+          c++ --version
+          xcode-select -print-path
+          python3 -m pip install setuptools
+
+          for i in {1..5}; do # try 5 times
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
+              exit 1
+            fi
+            echo "Npm install failed $i, trying again..."
+          done
+
+      - name: Create node_modules archive
+        if: steps.cache-node-modules.outputs.cache-hit != 'true'
+        run: |
+          set -e
+          node build/azure-pipelines/common/listNodeModules.js .build/node_modules_list.txt
+          mkdir -p .build/node_modules_cache
+          tar -czf .build/node_modules_cache/cache.tgz --files-from .build/node_modules_list.txt
+
+      - name: Create .build folder
+        run: mkdir -p .build
+
+      - name: Prepare built-in extensions cache key
+        run: node build/azure-pipelines/common/computeBuiltInDepsCacheKey.js > .build/builtindepshash
+
+      - name: Restore built-in extensions cache
+        id: cache-builtin-extensions
+        uses: actions/cache@v4
+        with:
+          path: .build/builtInExtensions
+          key: "builtin-extensions-${{ hashFiles('.build/builtindepshash') }}"
+
+      - name: Download built-in extensions
+        if: steps.cache-builtin-extensions.outputs.cache-hit != 'true'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: node build/lib/builtInExtensions.js
+
+      - name: Transpile
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: npm run gulp transpile-client-esbuild transpile-extensions
